name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Update version.json
        run: |
          DATE=$(date -u +"%Y-%m-%d")
          BT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          jq -n --arg fecha "$DATE" --arg bt "$BT" '{fechaActualizacion: $fecha, buildTime: $bt}' > version.json
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add version.json
          git commit -m "chore: update version.json [skip ci]" || echo "no changes"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
